apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tpv-frontend"
  namespace: "development"
  labels:
    app: "tpv-frontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "tpv-frontend"
  template:
    metadata:
      labels:
        app: "tpv-frontend"
    spec:
      containers:
      - name: "tpv-frontend-sha256-1"
        image: "eu.gcr.io/bngo-app/tpv-frontend"
        imagePullPolicy: Always
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              key: API_URL
              name: tpv-frontend-secret
