
name: Development CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [10.x, 12.4]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm run lint
  #   - run: npm run test:unit -- --ci

  cypress-run:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run serve &
    # https://github.com/cypress-io/github-action
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        working-directory: UI-e2e
        wait-on: 'http://localhost:8080'
